lexer grammar Scanner;
//Expresiones regulares
//Simbolos

LET:'let';
RETURN:'return';
ID: LETTER(LETTER|DIGIT)*;
EQUAL:'=';
PCOMA:';';
L:'<';
P:'>';
LE:'<=';
PE:'>=';
EE:'==';
SUM:'+';
SUB:'-';
MUL:'*';
DIV:'/';
PCI:'[';
PCD:']';
PRI:'(';
PRD:')';
DCOM:'"';
INTEGER:DIGIT(DIGIT|DIGIT)*;
STRING:DCOM LETTER(LETTER|SIGN)* DCOM;
TRUE:'true';
FALSE:'false';
LEN:'len';
FIRST:'first';
LAST:'last';
REST:'rest';
PUSH:'push';
FN:'fn' ID;
COMA:',';
LI:'{';
LD:'}';
DPTS:':';
PUTS:'puts';
IF:'if';
ELSE:'else';
SPACE:' ';
NUM:DIGIT (DIGIT)*;
OPERA:OPERATOR;
BOOLEAN:TRUE|FALSE;
fragment SIGN: EQUAL|PCOMA|L|P|OPERA|PCI|PCD|PRI|PRD|COMA|LI|LD|DPTS|LE|PE|EE|SPACE|NUM;
fragment LETTER :'a'..'z' | 'A'..'Z'|'_';
fragment DIGIT :'0'..'9';
fragment OPERATOR: '+'|'-'|'*'|'/';
WS : [ \t\n\r]+ -> skip;
LINE_COMMENT:   '//'.*?'\r'?'\n' -> skip ;
SPECIAL_COMMENT: '/*'( SPECIAL_COMMENT | . )*?'*/' -> skip;
